travis:
  secure:
    BINSTAR_TOKEN: dD7G6TfkhCA/+rDeAaps4RAEyKolql7Haxu4U2NKkgoqF5XOsvFKdLTcmxeNuKwzmUnfaNEeklGnEsEn18P0xgKQV6fdX07ngkWwFJZuV7X4a73heETiwQFd48yCFxMmhwynmUn5D9pSOsgLJv1gl+h97M/MPWjbBrftXglq9fsKQikj2EsC9dbOG8jB0QUHIp0ccRwW1V7FYZAVQfIC4f3KWGhwVxSZV6eEIWY4jK1y3tiZLfFjVXkn9c4XdT4bYJktpJKGdJJJUw5xZx/zzbLhmbsZleDigTQKqPy6nFBZmi9hLE0okZm+NeR7vSM/yohispzW6B3UpZfQ9jOPUTc9kMJ42URJCivMWuLx2vqMAv1rVesg1ACaXJssSk1iuLlPZQBTPLfOTi76gixz44bLvavjPn5/oEX6j2Q+k1uJQwNn8jMOr/84V0Nmm+2dvAsbF2cwsBN0MdIAusUO5Yvo2GZdPkIBTcvRBenU3vsmerSpeedqyEIViykDMux2pvvBhNAmXaXXnTawb2cUQYil5+CQU46/fy3n+jJNXbY6t7Ws4LxZ8UC4cvE4wBA4a1ghwQtheisTGsIiFbpLpTXJKn5B+dYtmUaLB03JzAoXqc16Tl734RHzXT/6VfD7f81QE0eJbcpU2+SFAi0ud/noCvxCr0EhqJxxrTLoQNA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
