travis:
  secure:
    BINSTAR_TOKEN: NH/eocCnPNuyfwzYqtbkEv2m9DkwHtSd5PRSyEAUzmL66r1iod0XiulXBqq1YRSj32tCTuhTIXQzB0EfuDljwB/WZTrYegootGirK7lRSyq3VtIvG3ry3ATkjC9dnN881zb6J6mTBaQY+sDrxfSCjZcPaQAnFkz4hNnxgWPKayZzYp7GYIExvbpp51sF81sEbflQwE8znwk25y8tUD6fi53wRsw0J4+YXebyG5epiJCWiUApYq9DkNwvaCVO0w8qjTcfsAUvPxMY3qwmtvwM3dZgqC0xpP2B40Jjqz5d7p0UA0OVppfln04Z2nL0gnJY23Rs4Geal096amlDGHc+i4PTarvsnjhMLMwPVPXEf2tl9XAC5YAthXRqTtQ26e8Yoqr9iLDsV8ueA1BAb3r7UQObWfwbIRqtozjNJ10vf9goEpgAiBBOBRwIXmE214IRr/J9YGw0IKIs+AYItH0LP9KaFsBXjRvSQonLW29E0o1ks5SVEw4hSC+bWIPoZHK/BrM9SoIl7CvOwHS8i7jSnUNClLyyqut+n6urmPTymbrWK/RQ1RPi392HMcoqsjsZsz0QtQyhy0pkIVe7JantH7/sNMfPn6ygiumSjZqLej5WgsrjrX9+brT/qUzfzbq8GMcovOqsVQrZ00TbuDJ9vNU9ULrEfjPBTe2L7I94Lng=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
