travis:
  secure:
    BINSTAR_TOKEN: xSjuqtYrxExH6waMqOK9BMhHT2xiHZhSdz8YWiW+08nY9IVsyWLQl1vN+7Zy/i/YCOiiy8T1wNAUMbjA+a36thAlfFoPSbGHHrXZn74Q9DsW+aLlf0vIQrGCqafuvc/pNp1mBBRCl79dMM5bPmm6IXIQwUHHXWU37WwRX9tLhhDe5hQDr5FJFGeURabZVt1gjT0fx1OPiGyFGVMCeU8fE9j9bl3FwVvTJ88TcC3hr8Zncb3Oe256ghI4sFTtrpjycWF0p72fVvCYLwf2mdcNctr9Z4BdQZAgCGWbkrNTSWynRfmsOP2PxnqwaZV9EEcOJUjA0bQnfwJhzZHcqcIohLjcK2WT9EhHIVFPqeqniJaGeboxPppBbrGd6PWt0K6hi9WlgfMuK7MkN9/HK26LcRbYX8qMNpPJn9aBIzxFup6Dw6TophyK+QKswGrLpNblWgqu2YQyiW5bWbgqYvSzVjAqoek113olKs1+JLN34Di5CI0FYgjx/kwQLlBz6FibPVBw2eT3y/dPaoZvSeY8WuU/FzQHvLQ+O1bFjFDBlLqSBXFrcYFOfotcRRVgH182e/ZnIJ2KH7G6bKd7kSqDgpDdeey5recF7+eMO3MBaby22IA0y3CyWzTm1eyXsY0/D5OGjpHZKsaHmOPRUVnLjTGZnMuNamGar3WnliFmRXM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
