travis:
  secure:
    BINSTAR_TOKEN: ODIfDwmdo5uVIiF9lQjCde+iewJGViKpAHRrT/FL75cH3Lg3HO1KfVWddPi22YU8dT4Ddz7+joIS14kC0GCLLP6hVi/PQiYoa9yQnLk2rIVaDsplkZ83wDTUbeVi7dBOgQGtFUExTscaWPZkzK3IpO2G56NEOJEe+MX/aInPms6t70IUOpkEFqGHPjxoPEuopgVUhps+OPqaqmai7X4xb0kUkaXb2nLBxUn8euqVjvAK0WbNR/TcrolN6rzhd5bnrw4FM7tQF3LSN0H5J7gYnkN+FDoeRdKy6KIvMbyawAOKxS3qd0YXgrUMF4ymLmvr+5QN6o+cfkerwAbIAHjkfRYUl18Ibcffif74wQb5LVCUkd3DkH0g/zTPSDEJAIUEH3M/k7G+LZZVJU+IAA+fKJcqZMNjcSMu53lG76rl137jFXos1BshCRENMxHKuaYZ7ETcDhvQ2OtRN75+w6I6E/pdSM6uGQAG0O9NbNtjny2Xcqgfz2bzEbePeWrbpjDxStDFBulbcVDrV0bNpDkb1IHutZIOlT4NX71TLQY1aDO2sS+LdpTe3TH8tKjpqVvlcCSMHhhQkmOCTeeMtvndg7CY058d4hRcKFllX6WS3vJpS6YnMOy9Nt+T6vWoFG/7DX5LWJVv9dU8l9ek8gL77cExbZsqgyQoJ3YaR49c99Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
